[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --theme repo"

[context.production]
  [context.production.environment]
    HUGO_VERSION = "0.39"
    HUGO_BASEURL = "https://hugo-onyx.netlify.com/"
