[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo"

[context.production]
  [context.production.environment]
    HUGO_BASEURL = "https://hugo-onyx.netlify.com/"

# PR previews
[context.deploy-preview]
  command = "cd exampleSite && hugo --baseURL ${DEPLOY_PRIME_URL}/"

[context.branch-deploy]
  command = "cd exampleSite && hugo --baseURL ${DEPLOY_PRIME_URL}/"
