[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo"

[context.production]
  [context.production.environment]
    HUGO_VERSION = "0.46"
    HUGO_BASEURL = "https://hugo-onyx.netlify.com/"
