name = "Onyx"
license = "BSD"
licenselink = "https://github.com/kaushalmodi/hugo-onyx-theme/blob/master/LICENSE.md"
description = "A documentation theme ported from the Hugo Alabaster theme"
homepage = "https://github.com/kaushalmodi/hugo-onyx-theme"
tags = ["documentation", "sphinx"]
features = []
min_version = 0.37

[author]
  name = "Kaushal Modi"
  homepage = "https://scripter.co"

# If porting an existing theme
[original]
  name = "Digitalcraftsman"
  homepage = "https://github.com/digitalcraftsman"
  repo = "https://github.com/digitalcraftsman/hugo-alabaster-theme"
